### ISSUE TITLE
How to submit new row as JSON?

### ISSUE THREAD

**Issue by georgeu2000** [openpsa/grid.js#130]
I have the following:

```
controller: {
    ....
    insertItem: function(item) {
        return $.ajax({
            type: "POST",
            contentType: "application/json",
            url: "/fields",
            data: item
        });
    },
```

I also tried `dataType: "json"`.

It is submitting the new item as form encoded.

What is the proper way to configure jsgrid to work with a JSON REST API?

**Comment by bouks** [comment]
Hi.

jsgrid does not send any json by itself.

This project was created in order to have a free and maintained version of tony tomov jqgrid.
But i think jsgrid is not maintained anymore.
I use it only on old projects, migrating to angular's grid on new projects.
If you're starting a new project, consider using another datagrid.

**Comment by georgeu2000** [comment]
It seems to me that there should be an easy way to integrate with a JSON REST API...

**Comment by georgeu2000** [comment]
Sorry, `dataType: "json"` does work. There was something else going on.

Also using [a different jsgrid](https://github.com/tabalinas/jsgrid).
