### ISSUE TITLE
reloadGrid raise error

### ISSUE THREAD

**Issue by bouks** [openpsa/grid.js#90]
When adding line i have an "opts is undefined"

that comes from :

https://github.com/meh-uk/grid.js/commit/fac62b7355d92b2805bf82f5889ea2f5ff950622#diff-2d010088e9cda4a876dbc3e2399c83a0R3107

See :

https://github.com/openpsa/grid.js/commit/d32b3b6a7343cbb6885d6c5b70be12dea7e4810f#commitcomment-9427236

Again a "merge" of Oleg's change that introduce bugs.
Also it breaks compatibility with 4.7.

We have decided not to break compatibility, so why this option come ?

**Comment by flack** [comment]
What code are you using and what browser? I tried the remote demo (http://openpsa.github.io/grid.js/demos/remote.html) and it doesn't throw an error (it doesn't work either, but that is a separate issue)

**Comment by bouks** [comment]
you said it, it doesn't work, so you can't add and have the bug.

Then when adding, there is the error and the new line is not filled (i don't know if same or different bug for the moment).

I'm really, but REALLY, annoyed with copy/paste of Oleg's commits.
These commits are not well tested, and i have to stop my (personnal job) work everytime for them.
That is not acceptable.

**Comment by flack** [comment]
Well, removing the `opts.fromServer` condition doesn't fix the problem AFAICT. We have only added it after we noticed that `reloadGrid` was broken (see the comments in the ticket you linked). The problem why it's not working is as far as I can tell some bad interaction between your autoloading code and Oleg's autoloading code.

It is obvious in retrospect that these changes from Oleg should not have been merged, but we did so in the hope that we could work together instead of having two independent projects. The bugs we have now are the price of our gesture of good will, so to speak. But we have stopped merging since, so once we get through the breakage we already have, there shouldn't be any new one.
